title: gmitch215
description: >
  Gregory is a fullstack developer from the United States. He loves to code and learn new things, and enjoys Math.

baseurl: ""
url: "https://gmitch215.dev"
github_username: gmitch215

markdown: kramdown
kramdown:
  parse_block_html: true
  parse_span_html: true